project:
  type: website
  output-dir: docs

website:
  title: "Kyle Wandel Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: Personal_Projects.qmd
        text: Personal Projects
      - href: School_Work.qmd
        text: School Work

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

